const swaggerAutogen = require('swagger-autogen')()
const outputFile = './swagger_output.json'
const endpointsFiles =
    [
        './controllers/player.js',
        './controllers/race.js',
    ]

const doc = {
    info: {
        version: "1.0.0",
        title: "Privilege Game API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Player",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        player: {
            $email: "jhon.doe@email.com",
            $occupation: 'analyst',
            $skin_tone: 5,
            $gender: 3
        },
        addPlayer: {
            $email: 'jhon.doe@email.com',
            $occupation: 'analyst',
            $skin_tone: 5,
            $gender: 3
        },
        race: {
            $id: 100,
            $name: "privilege game",
            description: "privilege game description",
            $total_players: 100,
            $has_prize: true,
            prize: "A cash prize of U$100.000,00",
            $lane_size: 100
        },
        addRace: {
            $name: "privilege game",
            description: "privilege game description",
            $total_players: 100,
            $has_prize: true,
            prize: "A cash prize of U$100.000,00",
            $lane_size: 100
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})