const swaggerAutogen = require('swagger-autogen')()
const outputFile = './swagger_output.json';
const Enums = require("./models/enums");
const endpointsFiles =
    [
        './controllers/player.js',
        './controllers/race.js',
        './controllers/session.js',
    ]

const doc = {
    info: {
        version: "1.0.0",
        title: "Privilege Game API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:4000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Player",
            "description": "Endpoints"
        }
    ],
    definitions: {
        player: {
            $id: 1,
            $email: "jhon.doe@email.com",
            $occupation: 'analyst',
            $is_leader: false,
            $skin_tone: 5,
            $gender: 3,
            $race: `race001`,
            score: 0,
            is_active: true,
        },
        addPlayer: {
            $id: 1,
            $email: 'jhon.doe@email.com',
            $occupation: 'analyst',
            $is_leader: false,
            $skin_tone: 5,
            $gender: 3,
            $race: 'race001'
        },
        race: {
            $id: "1",
            $name: "privilege game",
            description: "privilege game description",
            $total_players: 100,
            $has_prize: true,
            prize: "A cash prize of U$100.000,00",
            $lane_size: 100,
            status: Enums.READY,
            levels: [{
                $boundary: 30,
                $name: "Level 1"
            },{
                $boundary: 45,
                $name: "Level 2"
            }]
        },
        addRace: {
            $id: "1",
            $name: "privilege game",
            description: "privilege game description",
            $total_players: 100,
            $has_prize: true,
            prize: "A cash prize of U$100.000,00",
            $lane_size: 100,
            $questions:[
                {
                    $id: 1,
                    $content: 'Are your both parents graduated?',
                    $score: 1,
                    $type: 'Boolean',
                    $status: 'Open',
                }
            ]
        },
        updateRace: {
            name: "privilege game",
            description: "privilege game description",
            total_players: 100,
            has_prize: true,
            prize: "A cash prize of U$100.000,00",
            lane_size: 100,
            questions: [
                {
                    id: 1,
                    content: 'Are your both parents graduated?',
                    score: 1,
                    type: 'Range',
                    status: 'Close',
                }
            ]
        },
        session: {
            $id: 3,
            $name: "Session 001",
            $status: "Ready",
            $questions: {
                $content: "Are your both parents graduated?",
                $status: 'Close'
            }
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})